### ISSUE TITLE
[수정 요청] 회원가입 작동 안되는 문제

### ISSUE THREAD

**Issue by KOOJAESUNG** [Wiz-trip/Wiz-trip-Back#15]
안녕하세요 @kyungmin1221 님

Swagger를 통해 /users/signup 으로 회원가입을 하려 했으나, 
요청을 보냈을 때 DB에 insert가 되지 않는 것을 확인했습니다.

확인 결과, UserService의 createUser 메소드에 Transaction이 readonly로 처리되어 있어 작동하지 않는 것으로 보입니다.

수정 부탁드립니다.

또한, UserCreateForm에 ID를 의미하는 username attribute가 필요합니다. username이 없으면 spring security가 작동하지 않습니다.
추가 부탁드립니다.

**Comment by kyungmin1221** [comment]
요구사항에 맞게 수정했습니다

**Comment by kyungmin1221** [comment]
> 안녕하세요 @kyungmin1221 님
> 
> Swagger를 통해 /users/signup 으로 회원가입을 하려 했으나, 요청을 보냈을 때 DB에 insert가 되지 않는 것을 확인했습니다.
> 
> 확인 결과, UserService의 createUser 메소드에 Transaction이 readonly로 처리되어 있어 작동하지 않는 것으로 보입니다.
> 
> 수정 부탁드립니다.
> 
> 또한, UserCreateForm에 ID를 의미하는 username attribute가 필요합니다. username이 없으면 spring security가 작동하지 않습니다. 추가 부탁드립니다.

요구사항에 맞게 수정했습니다.

**Comment by KOOJAESUNG** [comment]
네 감사합니다 수정사항 확인 완료했습니다! 

이슈 닫도록 하겠습니다 :)
