### ISSUE TITLE
[질문] Image를 Entity로 변경 고려

### ISSUE THREAD

**Issue by KOOJAESUNG** [Wiz-trip/Wiz-trip-Back#26]
안녕하세요 @kyungmin1221 @moonxxpower 님!

Like 관련 최적화 중 의견을 묻고싶은 사항이 있습니다.

JPA 최적화를 위해 LandmarkEntity를 ResponseDto로 변환하는 과정에서 이미지를 한번에 불러오기 위해 fetch join을 사용하려 했으나,
현재 LandmarkEntity와 Image가 entity간의 연관관계가 아닌 elementcollection으로 되어있기 때문에 fetch join을 사용하지 못하고 있습니다.

fetch join을 사용하지 못하면, LandmarkEntity를 ResponseDto로 변환할 때 영속성 컨텍스트에 Image가 존재하지 않으므로 이를 불러오기 위해 불필요한 쿼리가 한번 더 나가는 문제가 생깁니다.

<img src="https://github.com/Wiz-trip/Wiz-trip-Back/assets/90593322/1745285a-1be4-4961-8114-58b72c24530f" width="40%">

따라서 이 문제를 해결하기 위해 Image를 값타입이 아닌 entity로 변경하는 것에 대해 다른 분들의 의견을 묻고 싶습니다.

**Comment by kyungmin1221** [comment]
문제 해결을 해결을 위해서 말씀해 주신 의견을 반영하는것이 좋아보입니다.

**Comment by moonxxpower** [comment]
불러오기 위해 불필요한 쿼리가 생성된다면 이미지 연관 관계를 맺어주는 것이 올바른 것 같습니다.
관련 글을 찾아보았는데, 이런 부분에서도 값 타입 대신 연관 관계를 맺어주는 것이 좋을 것 같아요.

https://velog.io/@kseysh/ElementCollection%EC%9D%98-%EA%B0%9C%EB%85%90%EA%B3%BC-%EC%A3%BC%EC%9D%98%ED%95%A0-%EC%A0%90

**Comment by KOOJAESUNG** [comment]
네 피드백 감사드립니다! 그러면 Image를 엔티티로 변경하도록 하겠습니다 :)
